### ISSUE TITLE
Not running on iOS 9.3.5 

### ISSUE THREAD

**Issue by FreeWind6** [damongolding/immich-kiosk#153]
I have an iPad 2 running iOS 9.3.5, but the Kiosk doesn't work in Safari  =( why?
What are the minimum requirements for Kiosk?

**Comment by damongolding** [comment]
I build Kiosk to work on > 0.2% of browsers. [https://browserslist.dev/?q=PiAwLjIl](https://browserslist.dev/?q=PiAwLjIl). IOS 9 is too old, are you able to upgrade the IOS or download a newer browser?

**Comment by FreeWind6** [comment]
Of course, this is not a problem =)

**Comment by feroxy** [comment]
Sorry to reopen. I'm looking at this project as a way to repurpose an old ipad 3 (which maxes at 9.3.5 also). Since using old ipads as photo frames seem to be an excellent way to avoid these old electronics becoming part of the e-waste problem, is there any appetite for producing a mode in Kiosk that caters to older devices/browsers? Even if that means sacrificing some of the fancier effects and such?

**Comment by redge76** [comment]
@feroxy  for Ipad I can recommend https://pixette.app/ 

There is even a solution to use immich https://github.com/immich-app/immich/discussions/1687#discussioncomment-11142789

**Comment by feroxy** [comment]
> @feroxy for Ipad I can recommend https://pixette.app/
> 
> There is even a solution to use immich [immich-app/immich#1687 (comment)](https://github.com/immich-app/immich/discussions/1687#discussioncomment-11142789)

Oddly enough I actually just stumbled on that the other day too and it works well. Good option, although I'm not sure pixette sees any further development for older IOS (or even if it can if there are publishing restrictions).
